# Generated by Django 3.2 on 2024-06-29 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserObjectStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500, verbose_name='file_name')),
                ('file_size', models.BigIntegerField(verbose_name='file_size')),
                ('uploaded_date_time', models.DateTimeField(auto_now_add=True, verbose_name='uploaded_date_time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_storages', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('users_added', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='users_added')),
            ],
        ),
    ]
